---
- name: Provision a persistent volume for Neo4j
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    zone: "{{ item }}"
    name: "{{ stack_name }}-mongo-{{ item }}"
    volume_size: 100
    volume_type: gp2
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"
  with_items: 
    - "{{ region }}a"
    - "{{ region }}b"
    - "{{ region }}c"
  register: ec2_vol_neo4j

- name: Provision a persistent volume for Neo4j Backup
  ec2_vol:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    zone: "{{ item }}"
    name: "{{ stack_name }}-mongo-{{ item }}"
    volume_size: 100
    volume_type: gp2
    tags:
      environment: "{{ environment_type }}"
      teamDL: "universal.publishing.platform@ft.com"
      systemCode: "{{ platform }}"
  with_items: 
    - "{{ region }}a"
  register: ec2_vol_neo4j_backup


# File System and Volume IDs for Neo4j and backup which needs to be added in the global config
- name: EBS details for Neo4j
  debug:
    msg: "EBS Volume IDs for Neo4j: '{{ ec2_vol_neo4j.volume_id }}'"

- name: EBS details for Neo4j backup
  debug:
    msg: "EBS Volume ID for Neo4j backup: '{{ ec2_vol_neo4j_backup.volume_id }}'"
